version: "2"
services:
  ui:
    build: ./UI
    links:
      - engine
    ports:
      - "5001:5000"
  engine:
    build: ./Engine
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: stefan
      MYSQL_USER: root
      MYSQL_PASSWORD: stefan
      MYSQL_DATABASE: database_drs    
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro